### ISSUE TITLE
Are you currently looking for a Google Wallet integration?

### ISSUE THREAD

**Issue by PrakiRikeki** [icp049/GoogleWallet_php#1]
I am currently looking for a solution how I can store my event tickets in Google Wallet for my guests.
You too?

**Comment by icp049** [comment]
Yes! I used this code to create google wallet passes for library customers. You need to setup things from the Google wallet console for the code to work though

**Comment by PrakiRikeki** [comment]
So your code already works and I can just copy it for my project?

**Comment by icp049** [comment]
Yep, just do composer install/update in project directory after forking. After that, you should set up your google wallet api in google wallet console and you should be able to have an "issuer id".. place that in the code and create a front end that makes a post request to wallet.php. I have included a mock html front end to demonstrate that.

**Comment by PrakiRikeki** [comment]
To run composer install I need a composer.json. Do you have such a file for me or do I have to put it together myself?

I solved the problem see my fork or this file
[composer.json](https://github.com/user-attachments/files/17043026/composer.json)

**Comment by icp049** [comment]
Sorry my bad, I forgot to include that.  I have uploaded the composer.json in the repository.

**Comment by PrakiRikeki** [comment]
That's no problem. I've already created it. A walletconfig.json was also missing.
Feel free to take a look at the whole thing in my fork.
