### ISSUE TITLE
Google Wallet shows an error message

### ISSUE THREAD

**Issue by PrakiRikeki** [icp049/GoogleWallet_php#6]
The following image shows the error message I receive when sending my document.
Can you explain the error or have you had this error in the past?

This is my current code status: fbdd273a491ce05cbb48522a4cdb80428d431926

![grafik](https://github.com/user-attachments/assets/68401f0a-95a2-4fc1-a51f-ddc028e8a2b0)

**Comment by icp049** [comment]
Hello, have you set up your google wallet api? Do you already have your issuer id and your walletconfig.json?
Also make sure that when you activate the google wallet api.. Put the email that youre testing in the test accounts.

**Comment by icp049** [comment]
here is a guide to make a service account under your google wallet and produce a walletconfig.json for that account https://developers.google.com/wallet/generic/getting-started/auth/rest

**Comment by PrakiRikeki** [comment]
ist works!

but you have to use the following config.
It would be nice if you could change that

$genericObject = [
    'id' => 'ISSUER_ID.OBJECT_ID',
    'classId' => 'ISSUER_ID.GENERIC_CLASS_ID',
    'logo' => [
        'sourceUri' => [
            'uri' => 'https://storage.googleapis.com/wallet-lab-tools-codelab-artifacts-public/pass_google_logo.jpg'
        ],
        'contentDescription' => [
            'defaultValue' => [
                'language' => 'en-US',
                'value' => 'LOGO_IMAGE_DESCRIPTION'
            ]
        ]
    ],
    'cardTitle' => [
        'defaultValue' => [
            'language' => 'en-US',
            'value' => '[TEST ONLY] Google I/O'
        ]
    ],
    'subheader' => [
        'defaultValue' => [
            'language' => 'en-US',
            'value' => 'Attendee'
        ]
    ],
    'header' => [
        'defaultValue' => [
            'language' => 'en-US',
            'value' => 'Alex McJacobs'
        ]
    ],
    'textModulesData' => [
        [
            'id' => 'points',
            'header' => 'POINTS',
            'body' => '1112'
        ],
        [
            'id' => 'contacts',
            'header' => 'CONTACTS',
            'body' => '79'
        ]
    ],
    'barcode' => [
        'type' => 'QR_CODE',
        'value' => 'BARCODE_VALUE',
        'alternateText' => ''
    ],
    'hexBackgroundColor' => '#4285f4',
    'heroImage' => [
        'sourceUri' => [
            'uri' => 'https://storage.googleapis.com/wallet-lab-tools-codelab-artifacts-public/google-io-hero-demo-only.png'
        ],
        'contentDescription' => [
            'defaultValue' => [
                'language' => 'en-US',
                'value' => 'HERO_IMAGE_DESCRIPTION'
            ]
        ]
    ]
];

**Comment by icp049** [comment]
Did it work for you? Are you now able to generate the sample pass? Also, the object format i used is for generic card type only. Other google cards are formatted in a different way

**Comment by PrakiRikeki** [comment]
Unfortunately I couldn't create a passport using your template. But when I used the example shown above, it worked. I can only create generic card types now
